google_drive_screenshot_folder: Blue Prince
google_drive_secrets_dir: /Users/michael.myung/.blueprince_mcp
obsidian_vault_path: /Users/michael.myung/Documents/blueprince_mcp
root: /Users/michael.myung/dev/blueprince-mcp
server:
    host: localhost
    port: 8001
